kind: ImageStreamList
apiVersion: v1
metadata:
  name: springboot-image-streams
  annotations:
    description: ImageStream definitions for Springboot Application images
    openshift.io/provider-display-name: Ricardo Zanini
items:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: springboot-ubi8
    annotations:
      openshift.io/display-name: Runtime image for Java Applications based on SpringBoot
      openshift.io/provider-display-name: Ricardo Zanini
  spec:
    tags:
    - name: '0.1.0'
      annotations:
        description: Runtime image for Java Applications based on SpringBoot
        iconClass: icon-java
        tags: runtime,java,springboot
        supports: springboot
        version: '0.1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: quay.io/ricardozanini/springboot-ubi8:0.1.0
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: springboot-ubi8-s2i
    annotations:
      openshift.io/display-name: Platform for building Java Applications based on SpringBoot
      openshift.io/provider-display-name: Ricardo Zanini
  spec:
    tags:
    - name: '0.1.0'
      annotations:
        description: Platform for building Java Applications based on Springboot
        iconClass: icon-java
        tags: builder,java,springboot
        supports: springboot
        version: '0.1.0'
      referencePolicy:
        type: Local
      from:
        kind: DockerImage
        name: quay.io/ricardozanini/springboot-ubi8-s2i:0.1.0